Dev fsx
thinkstack-co/terraform-modules pull request #103
Opened 2022-07-21 12:34 UTC by jakeasarus

Created new fsx module with the following resources:

- data sources
- FSx instance using self managed AD
- KMS keys
- Cloudwatch log group

Verified that FSx instance is created, placed in specified OU, joined to the domain, generates aliases, and is accessible. 

For this module it will be required to put variables inside of the terraform workspace with the FSx service account credentials. 

Still need to add a readme, but creating PR for visibility for Zach. Will update once README.md is created.

2022-07-21 12:35 UTC, jakeasarus commented
Example of code running successfully: https://app.terraform.io/app/thinkstack-co/workspaces/alps_prod_infrastructure/runs/run-B38Hc7EVGsVV7yD7

2022-07-21 19:54 UTC, zachreborn requested changes

2022-07-21 19:54 UTC, zachreborn commented on modules/aws/fsx/main.tf
> +                    "kms:EncryptionContext:aws:logs:arn": "arn:aws:logs:${data.aws_region.current.name}:${data.aws_caller_identity.current.account_id}:log-group:*"
This line might need tweaking. As it is written it will only allow encrypting and decrypting for your cloudwatch log group. If FSX is encrypted with this KMS key you'll also need to add another rule in here that allows the FSX arn to do the same.

2023-02-21 20:12 UTC, zachreborn approved these changes

2023-02-21 20:12 UTC, merged