Dev s3 lifecycle
thinkstack-co/terraform-modules pull request #115
Opened 2022-10-10 18:54 UTC by jakeasarus

2022-10-10 18:59 UTC, jakeasarus commented
### S3 Lifecycle Policies Feature

1. Adds ability to set a lifecycle policy with 1 action. 
2. Bool using count to either true/false to create a lifecycle rule. (defaults to false)
3. Ability to create lifecycle policy, but have it be disabled for troubleshooting. 
4. Allows prefix to set a subdirectory where rule starts. 

**Successful terraform run using branch**
[Terraform Plan](https://app.terraform.io/app/thinkstack-co/workspaces/solarity_prod_infrastructure/runs/run-cDdBttBzt5Srm6vU)

Umbrella bucket was updated to test the default to false, lifecycle was not created. 
Cloudberry bucket was set to true to keep the bucket from growing to 11TB again. Lifecycle rule created. 

[Merge commit](https://github.com/thinkstack-co/solarity_prod_infrastructure/pull/252)

2022-10-10 20:21 UTC, zachreborn requested changes
A couple syntax changes is all

2022-10-10 20:21 UTC, zachreborn commented on modules/aws/s3/main.tf
> +  count  = (var.lifecycle_rule_create == true ? 1 : 0)
I believe that the latest syntax best practices on this would be:
`count = var.lifecycle_rule_create ? 1 : 0`

2022-10-10 20:21 UTC, zachreborn commented on modules/aws/s3/variables.tf
> +  default     = ""
default = null
This is better for strings because i've noticed the AWS provider defaulting to NULL for strings and lists as opposed to empty strings or empty lists

2022-10-10 20:21 UTC, zachreborn commented on modules/aws/s3/variables.tf
>    default     = ""
default = null
This is better for strings because i've noticed the AWS provider defaulting to NULL for strings and lists as opposed to empty strings or empty lists.

2023-03-17 19:24 UTC, zachreborn approved these changes

2023-03-22 02:49 UTC, zachreborn commented
This module overhauls the following:
- All S3 modules have moved to the S3 folder -> 'modules/aws/s3/'
- The legacy S3 modules have been moved as well
- Rebuilt the S3 module to use the latest configuration where S3 resources are managed via multiple resource blocks for bucket, lifecycle, encryption, etc
- The S3 module itself can now handle more advanced configuration instead of needing so many separate S3 modules

2023-03-22 02:49 UTC, merged