fixed the s3 endpoint in the vpc module
thinkstack-co/terraform-modules pull request #33
Opened 2021-02-03 21:19 UTC by tgallagher91

2021-02-03 21:19 UTC, tgallagher91 commented
this actually fixes the issue

2021-02-03 21:38 UTC, jakeasarus requested changes
Need to fix misspelling of 'data' on line 197, currently says 'ddata'

2021-02-03 21:38 UTC, jakeasarus commented on modules/aws/vpc/main.tf
> +ddata "aws_vpc_endpoint_service" "s3" {
misspelled data

2021-02-03 21:40 UTC, tgallagher91 commented on modules/aws/vpc/main.tf
> +ddata "aws_vpc_endpoint_service" "s3" {
i have no idea how the code worked with DATA MISPELLED

2021-02-03 21:52 UTC, jakeasarus reviewed
looks better. @tgallagher91 also tested the module before pulling in to verify that broken runs are now successful.

2021-02-03 21:52 UTC, jakeasarus approved these changes
lgtm

2021-02-22 20:26 UTC, jakeasarus commented
made minor syntax updates to remove count. Know working with this run: https://app.terraform.io/app/thinkstack-co/workspaces/peoples_prod_uswest2_infrastructure/runs/run-znhs7phqfpYx5XqV

ready for approval.

2021-02-22 20:58 UTC, zachreborn requested changes
Can you rename back to outputs.tf please?

2021-02-22 20:58 UTC, zachreborn commented on modules/thinkstack/siem/outputs-Jacob’s MacBook Pro.tf
> +output "private_subnet_ids" {
Any reason we changed the outputs file name? @jakeasarus

2021-02-22 21:25 UTC, jakeasarus commented on modules/thinkstack/siem/outputs-Jacob’s MacBook Pro.tf
> +output "private_subnet_ids" {
mistake. fixed!

2021-02-22 22:06 UTC, zachreborn approved these changes

2021-02-22 22:06 UTC, merged