Dev flow log build
thinkstack-co/terraform-modules pull request #51
Opened 2021-11-24 22:38 UTC by zachreborn

New module which automates the flow log requirements creation

2021-11-24 22:49 UTC, TheJalpa requested changes
Have a couple of things requested for review

2021-11-24 22:49 UTC, TheJalpa commented on modules/aws/flow_logs/main.tf
> +data "aws_iam_role" "this" {
do we have a different name we can give this?

2021-11-24 22:49 UTC, TheJalpa commented on modules/aws/flow_logs/variables.tf
> +    type = string
We can leave this as / if we want - but it might make it easier to reduce the possibility of policy conflicts if we give this something like /flow_log/ to the policy path gets put in a more specific place in the event a customer ends up with similar resources in their stock environment.

2021-11-24 22:49 UTC, TheJalpa commented on modules/aws/flow_logs/variables.tf
> +  default     = false
Do we want these set to default as false? This might result in a terraform destroy failing if we remove the module which would require manual intervention (unless that's intentional)

2021-11-25 14:54 UTC, zachreborn commented on modules/aws/flow_logs/variables.tf
> +    type = string
Likely something for the future. Nested objects and folders for IAM policies could be good to deploy if we come up with a standard. For now they'd probably change and result in more maintenance later.

2021-11-25 14:55 UTC, zachreborn commented on modules/aws/flow_logs/variables.tf
> +  default     = false
Yeah, my thought is with some of these that the default behavior (which is false) is likely the best for now. I'd rather it error out prior to a destroy if someone had attached additional policies to this role because it could highlight that the role is in use elsewhere and incorrectly.

2021-11-25 17:48 UTC, TheJalpa approved these changes
Looks good

2021-11-26 13:33 UTC, merged